---
title: "ESS Exploration *Need to Change*"
author: Basil Wong, Tamsen Yau, Ashas Memon
thanks: "Code and data are available at: https://github.com/ashasmemon/ESSExploration"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "This report aims to examine ... "
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE, show_col_types = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(knitr)
library(kableExtra)
```

# Questionaire Discussion

Some questions present in the European Social Survey (ESS) aim to quantify qualitative measures such as those asking about happiness and emotions. Each respondent can select from a scale of 00-10 and they also have the option for “refusal” or “don’t know”. The benefit for the latter two options provides a convenience because all questions responded with “refusal” can be discarded (Verify how refusals are handled in this survey). A better option for “refusal” is “Don’t know” because participants are more likely to respond with a “Don’t know” as compared to a “refusal”. A benefit to this is that this particular question can be ignored rather than discarding all information from all questions for a particular respondent (IncludeNeutralPointInQuestionsCitation).

It is however a good measure for determinize how someone perceives their current condition with some limitations. For example, Question C1 (Taking all things together, how happy would you say you are?). Questions C9 and C10 aim to quantify how emotionally attached the respondent feels towards their own country and Europe respectively. All three of these questions expect a response on a scale from 00-10 but it is challenging to compare the same response for two people. If two people select 06 for question C1, how can we be sure that they are equally happy? Similarly, how can policymakers be sure that someone who selected 06 is in fact less happy than someone who selects 07 or is happier than someone who selects 05. Extending this further, how can one be certain that someone who select 06 is in fact twice as happy as someone who selects 03. Additionally, for question C9 and C10, how can we compare two people who both selected 06 for their emotional attachment to their country and Europe, how do we ensure that both people are equally emotionally attached given the same response? (ProblemsWithMeasuringHappinessCitation)

Trying to quantify such qualitative measures is difficult because the questioned mentioned above (Include these questions in a table) require a subjective opinion which may depend on a person’s own socioeconomic status, culture, environment, psychological or their mood at this particular instance. All of these lead to ambiguity in the responses for such questions.

Furthermore, there are also some questions which require a binary response (yes and no) to avoid any ambiguity in the responses. For example, question C13 and C18 whether the respondent considers themselves to be religious and whether they would describe themselves a member of a group that is discriminated against in their country respectively (see figure). Although a yes/no style question removes any ambiguity it might raise additional questions when the respondent does not fully match the criteria for the provided possible responses. In the case of question C13, if someone is religious sometimes, they might consider themselves somewhere in between the “yes” and “no” options. But given the current responses of “yes”, “no” “refusal” and “Don’t know”, they might lean towards selecting “Don’t know” because they don’t see an option that best describes their response. (YesNoQuestionsCitation )

Along with some shortcomings discussed above, there is flexibility in this questionnaire because it provides a wide range of options for the respondent to choose from. This limits the chances of there being any common options left out. In addition to this, various questions, including C19, C21, C23, C24, C25, C28, C30 also allow for the respondent to enter their own response if their response cannot be categorized among the provided options or if the question requires a response that will be different for each person such as C24 asking about a the year the respondent came to the particular country. Refer to table for the corresponding questions. 


